# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
"https://url.v1.mk/sub?target=clashr&url=vmess%3A%2F%2FeyJob3N0IjoiIiwicGF0aCI6IiIsInRscyI6IiIsInZlcmlmeV9jZXJ0Ijp0cnVlLCJhZGQiOiJ3eHBsY3Qua2ttYm5iZy54eXoiLCJwb3J0IjoiMTIwMDIiLCJhaWQiOiIwIiwibmV0IjoidGNwIiwiaGVhZGVyVHlwZSI6Im5vbmUiLCJ2IjoiMiIsInR5cGUiOiJub25lIiwicHMiOiLwn4e68J%2BHsiBDTjItVjIxMy3nvo7lm70tMXgtTkYmSEJPJkh1bHUmRGlzbmV5KiIsInJlbWFyayI6IvCfh7rwn4eyIENOMi1WMjEzLee%2BjuWbvS0xeC1ORiZIQk8mSHVsdSZEaXNuZXkqIiwiaWQiOiI1NWJiZDM5Mi1mZjM4LTM4YzItYmRmNy05NmZkM2E1NmIwNmIiLCJjbGFzcyI6M30%3D%7Cvless%3A%2F%2Ff27d18ff-66e9-47de-becf-7e1222afa388%4047.239.223.50%3A31333%2F%3Ftype%3Dtcp%26security%3Dnone%23%25E9%25A6%2599%25E6%25B8%25AF%7Cvless%3A%2F%2Ffc0c7cd3-9d8d-4fac-b590-6b27fd763f76%40test2.quickfastinvest.top%3A443%2F%3Ftype%3Dws%26security%3Dtls%26path%3D%252Fsadertgfgfd%26sni%3Dtest2.quickfastinvest.top%23%25E2%259C%25A8%25E7%25BE%258E%25E5%259B%25BD%25F0%259F%2587%25BA%25F0%259F%2587%25B8CF2LESS%7Cvmess%3A%2F%2FewogICJ2IjogIjIiLAogICJwcyI6ICIwMDciLAogICJhZGQiOiAiMTA3LjE3NC4xMzMuMTIyIiwKICAicG9ydCI6IDUwOTQxLAogICJpZCI6ICIyNDMyM2JkNy1mYjY4LTRjMjQtOGNmMi1jODgwZjRjYTAxNTkiLAogICJhaWQiOiAwLAogICJuZXQiOiAidGNwIiwKICAidHlwZSI6ICJub25lIiwKICAiaG9zdCI6ICIiLAogICJwYXRoIjogIiIsCiAgInRscyI6ICJub25lIgp9%7Cvmess%3A%2F%2FeyJ2IjoiMiIsInBzIjoidCIsImFkZCI6IjEzNi4xNzUuMTc3Ljk1IiwicG9ydCI6IjEyNzM4IiwiaWQiOiI0YWY4ZWE0Mi00NTJlLTRmNjctOTI1Ni0yNjEwZjEzYzAwMWYiLCJ0eXBlIjoibm9uZSIsIm5ldCI6InRjcCIsInNlY3VyaXR5IjoiYXV0byJ9%7Cvmess%3A%2F%2FeyJ2IjoiMiIsInBzIjoiVVNPMiIsImFkZCI6IjIwNS4yMzQuMjQ0LjM2IiwicG9ydCI6IjQ0MyIsImlkIjoiZWY0NjMwZmQtZDAyNC00OTVhLWJjNGEtOWVmNWFmMWYyMzRkIiwidHlwZSI6Im5vbmUiLCJuZXQiOiJ0Y3AiLCJzZWN1cml0eSI6ImF1dG8ifQ%3D%3D%7Cvmess%3A%2F%2FeyJ2IjoiMiIsInBzIjoiNjYuMjI1LjIyOC41NToxMzExNyIsImFkZCI6IjY2LjIyNS4yMjguNTUiLCJwb3J0IjoiMTMxMTciLCJpZCI6ImI5NTc4YTcyLTY2MDctNDdkZC1mMGM4LTMyYTk0YjBhMmZmOSIsImhvc3QiOiIiLCJwYXRoIjoiL2dyZGFnYSIsIm5ldCI6IndzIiwic2VjdXJpdHkiOiJhdXRvIn0%3D%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIkZhbm5pIE1vYmlsZSIsDQogICJhZGQiOiAic3VwcG9ydC5zLWItay5pciIsDQogICJwb3J0IjogIjUxOTY4IiwNCiAgImlkIjogIjhjYzZmYTFjLTViOWMtNGQxMS1kMzc3LWMxN2E5NzM5MmFjMCIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiLyIsDQogICJ0bHMiOiAidGxzIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9%7Cvless%3A%2F%2Fb9b6d776-3063-471e-849a-4b23675ae104%4038.147.163.106%3A14844%3Fencryption%3Dnone%26flow%3Dxtls-rprx-vision%26security%3Dreality%26sni%3Dwww.microsoft.com%26fp%3Dchrome%26pbk%3DWO8we7ZpUgG66kY4UZDD0hGx_7IxOWA8ITXlcN2zGxM%26sid%3D818cf516%26type%3Dtcp%26headerType%3Dnone%23vls%7Cvless%3A%2F%2Fe6a83c8d-5330-4af1-ad33-f78e3e782e74%40test.dzli94.sbs%3A8443%3Fencryption%3Dnone%26security%3Dtls%26sni%3Dtest.dzli94.sbs%26type%3Dws%26host%3Dtest.dzli94.sbs%26path%3D%252F5330%23host8443vless5%7Cvmess%3A%2F%2Few0KICAidiI6ICIyIiwNCiAgInBzIjogIjE1XHU1RTc0XHU4QkMxXHU0RTY2IiwNCiAgImFkZCI6ICIxLmFwc2tlbC5zaG9wIiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogIjg1NmVmMWI2LWRmZTktNGUyMC1mZmNkLTk2YzJhYTVhYTAxYiIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiMS5hcHNrZWwuc2hvcCIsDQogICJwYXRoIjogIi9waWsiLA0KICAidGxzIjogInRscyIsDQogICJzbmkiOiAiMS5hcHNrZWwuc2hvcCIsDQogICJhbHBuIjogIiIsDQogICJmcCI6ICIiDQp9&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_AdblockPlus.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false"
"vless://30c35b3c-e146-427f-8bc9-72953d345ae4@107.172.76.33:35552?type=kcp&headerType=srtp&seed=iJHy6oAf9L&security=none#recknard-207ktsmo"
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}_${CITY}_${ISP}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = true
# 代理节点池
pools = [
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "http://www.google.com/generate_204"
expected = 204
timeout = 500

# 带宽测速配置
[speed_test]
enabled = false
url = "https://speed.cloudflare.com/__down?bytes=104857600"
timeout = 3000
